export const userTypes={
    SIGNUP_USER:'SIGNUP_USER',
    LOGIN_USER:'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    PROFILE_USER: 'PROFILE_USER',
    PROFILEPIC_USER: 'PROFILEPIC_USER',
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    SET_AUTH: 'SET_AUTH',
}

export const postTypes={
    ADD_POST:'ADD_POST',
    FETCH_ALL_POST:'FETCH_ALL_POST',
    FETCH_COMMENTS:'FETCH_COMMENTS',
    COMMENT_POST: 'COMMENT_POST',
    LIKE_POST: 'LIKE_POST',
    ACTIVE_POST: 'ACTIVE_POST'
}

export const blogTypes={
    FETCH_ALL_BLOGERS:'FETCH_ALL_BLOGERS',
    FETCH_BLOGER:'FETCH_BLOGER',
    SWITCH_MODE:'SWITCH_MODE',
    
}

export const chatTypes={
    FETCH_CHATSEC:'FETCH_CHATSEC',
    FETCH_MESSEGES:'FETCH_MESSEGES',
    SEND_MESSEGE:'SEND_MESSEGE',
    SET_LOGINUSERS:'SET_LOGINUSERS',
    CONNECT_SOCKET: 'CONNECT_SOCKET'
    
}